import { execFileSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

export const G2E_PROVENANCE_SCHEMA_VERSION = "g2e-build-provenance-v1";
export const G2E_REPOSITORY_COMMIT_ENV = "G2E_REPOSITORY_COMMIT";
export const G2E_PROVENANCE_OUTPUT =
  "build/g2e-provenance/G2eBuildProvenance.luau";

const COMMIT_PATTERN = /^[0-9a-f]{40}$/;

export type G2eProvenanceSource = "environment" | "git";

export type G2eProvenanceResolution = Readonly<{
  repositoryCommit: string;
  source: G2eProvenanceSource;
}>;

export class G2eProvenanceError extends Error {
  readonly code: string;
  readonly field: string;

  constructor(code: string, field: string, message: string) {
    super(message);
    this.name = "G2eProvenanceError";
    this.code = code;
    this.field = field;
  }
}

function validateCommit(value: string, source: G2eProvenanceSource): string {
  const commit = source === "git" ? value.trim() : value;
  if (!COMMIT_PATTERN.test(commit)) {
    throw new G2eProvenanceError(
      source === "environment"
        ? "g2e-provenance-invalid-override"
        : "g2e-provenance-invalid-git-commit",
      source === "environment" ? G2E_REPOSITORY_COMMIT_ENV : "gitHead",
      `${source} commit must be exactly 40 lowercase hexadecimal characters`,
    );
  }
  return commit;
}

export function readGitRepositoryCommit(): string {
  try {
    return execFileSync("git", ["rev-parse", "HEAD^{commit}"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch {
    throw new G2eProvenanceError(
      "g2e-provenance-git-unavailable",
      "gitHead",
      `Git metadata is unavailable; set ${G2E_REPOSITORY_COMMIT_ENV} to an explicitly reviewed 40-character lowercase commit SHA`,
    );
  }
}

export function resolveG2eRepositoryCommit(options?: {
  override?: string;
  readGitHead?: () => string;
}): G2eProvenanceResolution {
  if (options?.override !== undefined) {
    return Object.freeze({
      repositoryCommit: validateCommit(options.override, "environment"),
      source: "environment",
    });
  }

  const readGitHead = options?.readGitHead ?? readGitRepositoryCommit;
  let gitHead: string;
  try {
    gitHead = readGitHead();
  } catch (error) {
    if (error instanceof G2eProvenanceError) throw error;
    throw new G2eProvenanceError(
      "g2e-provenance-git-unavailable",
      "gitHead",
      `Git metadata is unavailable; set ${G2E_REPOSITORY_COMMIT_ENV} to an explicitly reviewed 40-character lowercase commit SHA`,
    );
  }
  return Object.freeze({
    repositoryCommit: validateCommit(gitHead, "git"),
    source: "git",
  });
}

export function renderG2eBuildProvenance(repositoryCommit: string): string {
  const commit = validateCommit(repositoryCommit, "environment");
  return [
    "-- Generated by tools/prepare-g2e-build.ts. Do not edit.",
    "return table.freeze({",
    `    schemaVersion = "${G2E_PROVENANCE_SCHEMA_VERSION}",`,
    `    repositoryCommit = "${commit}",`,
    "})",
    "",
  ].join("\n");
}

export async function writeG2eBuildProvenance(
  outputPath: string,
  repositoryCommit: string,
): Promise<void> {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(
    outputPath,
    renderG2eBuildProvenance(repositoryCommit),
    "utf8",
  );
}
